"""Software-development lexicon for glossary extraction.

Terms here are likely to be mistranslated or inconsistently rendered in Farsi.
Suggestions are optional starter translations (user can override on the glossary page).
"""

from __future__ import annotations

# Multi-word phrases first (matched case-insensitively as whole phrases).
# Longer phrases should appear before shorter ones when scanning.
MULTIWORD_TERMS: dict[str, str] = {
    "package manager": "مدیر بسته",
    "package management": "مدیریت بسته",
    "purely functional": "کاملاً تابعی / pure functional",
    "functional package manager": "مدیر بستهٔ تابعی",
    "nix store": "انبار نیکس (Nix store)",
    "nix expression": "عبارت نیکس (Nix expression)",
    "nix expressions": "عبارات نیکس",
    "nix packages collection": "مجموعهٔ بسته‌های نیکس (Nixpkgs)",
    "binary cache": "کش باینری",
    "source deployment": "استقرار از سورس",
    "binary deployment": "استقرار باینری",
    "garbage collector": "جمع‌کنندهٔ زباله (garbage collector)",
    "garbage collection": "جمع‌آوری زباله",
    "atomic upgrade": "ارتقای اتمی",
    "atomic upgrades": "ارتقاهای اتمی",
    "roll back": "بازگردانی (rollback)",
    "side-effect": "اثر جانبی",
    "side-effects": "اثرات جانبی",
    "side effect": "اثر جانبی",
    "side effects": "اثرات جانبی",
    "runtime dependency": "وابستگی زمان اجرا",
    "runtime dependencies": "وابستگی‌های زمان اجرا",
    "build dependency": "وابستگی ساخت",
    "build dependencies": "وابستگی‌های ساخت",
    "build script": "اسکریپت ساخت",
    "environment variable": "متغیر محیطی",
    "environment variables": "متغیرهای محیطی",
    "system configuration": "پیکربندی سیستم",
    "configuration file": "فایل پیکربندی",
    "configuration files": "فایل‌های پیکربندی",
    "boot loader": "بارگذار راه‌اندازی (boot loader)",
    "boot menu": "منوی راه‌اندازی",
    "disk image": "تصویر دیسک",
    "virtual machine": "ماشین مجازی",
    "test environment": "محیط آزمایش",
    "production server": "سرور عملیاتی (production)",
    "mutable state": "وضعیت تغییرپذیر (mutable state)",
    "declarative configuration": "پیکربندی اعلانی",
    "cryptographic hash": "هش رمزنگاری‌شده",
    "dependency graph": "گراف وابستگی",
    "build process": "فرایند ساخت",
    "multi-user": "چندکاربره",
    "non-privileged": "بدون دسترسی ویژه",
    "source code": "کد منبع",
    "operating system": "سیستم‌عامل",
    "system service": "سرویس سیستم",
    "system services": "سرویس‌های سیستم",
    "dll hell": "جهنم DLL",
    "trojan horse": "اسب تروا",
    "pre-built": "ازپیش‌ساخته",
    "from source": "از روی سورس",
}

# Single-token tech terms → suggested Farsi (or “keep Latin”).
SINGLE_TERMS: dict[str, str] = {
    # Nix ecosystem
    "nix": "Nix (نام محصول — لاتین بماند)",
    "nixos": "NixOS (لاتین بماند)",
    "nixpkgs": "Nixpkgs (لاتین بماند)",
    "derivation": "derivation / اشتقاق ساخت",
    "derivations": "derivations / اشتقاق‌های ساخت",
    "store": "store / انبار (Nix store)",
    "profile": "profile / نمایهٔ کاربر",
    "profiles": "profiles / نمایه‌ها",
    "flake": "flake",
    "flakes": "flakes",
    "narinfo": "narinfo",
    "channel": "channel / کانال",
    "channels": "channels / کانال‌ها",
    # Packaging / builds
    "package": "بسته",
    "packages": "بسته‌ها",
    "dependency": "وابستگی",
    "dependencies": "وابستگی‌ها",
    "depend": "وابسته بودن",
    "install": "نصب",
    "installation": "نصب",
    "uninstall": "حذف نصب",
    "upgrade": "ارتقاء",
    "upgrades": "ارتقاها",
    "rollback": "بازگردانی (rollback)",
    "rollbacks": "بازگردانی‌ها",
    "build": "ساخت (build)",
    "builds": "ساخت‌ها",
    "rebuild": "بازساخت",
    "compile": "کامپایل",
    "compiling": "در حال کامپایل",
    "compiler": "کامپایلر",
    "binary": "باینری",
    "binaries": "باینری‌ها",
    "source": "سورس / منبع",
    "sources": "سورس‌ها",
    "artifact": "آرتیفکت",
    "artifacts": "آرتیفکت‌ها",
    "cache": "کش",
    "cached": "کش‌شده",
    "hash": "هش",
    "hashes": "هش‌ها",
    "hashing": "هش‌کردن",
    "symlink": "پیوند نمادین (symlink)",
    "symlinks": "پیوندهای نمادین",
    "path": "مسیر",
    "paths": "مسیرها",
    "overwrite": "بازنویسی",
    "overwritten": "بازنویسی‌شده",
    "deterministic": "قطعی / reproducible از نظر نتیجه",
    "reproducible": "بازتولیدپذیر",
    "isolation": "ایزوله / جداسازی",
    "isolated": "ایزوله‌شده",
    "atomic": "اتمی (atomic)",
    "transactional": "تراکنشی",
    "declarative": "اعلانی (declarative)",
    "imperative": "امری (imperative)",
    "functional": "تابعی (functional)",
    "pure": "خالص (pure)",
    "impure": "ناخالص",
    "runtime": "زمان اجرا",
    "compile-time": "زمان کامپایل",
    # Systems
    "kernel": "هسته (kernel)",
    "daemon": "daemon / خدمت پس‌زمینه",
    "service": "سرویس",
    "services": "سرویس‌ها",
    "process": "فرایند",
    "processes": "فرایندها",
    "privilege": "سطح دسترسی",
    "privileged": "با دسترسی ویژه",
    "user": "کاربر",
    "users": "کاربران",
    "boot": "راه‌اندازی",
    "reboot": "راه‌اندازی مجدد",
    "filesystem": "سیستم فایل",
    "directory": "دایرکتوری",
    "directories": "دایرکتوری‌ها",
    "library": "کتابخانه",
    "libraries": "کتابخانه‌ها",
    "linker": "لینکر",
    "loader": "لودر",
    "shell": "شل",
    "bash": "Bash",
    "ssh": "SSH",
    "sshd": "sshd",
    "openssl": "OpenSSH/OpenSSL",
    "openssh": "OpenSSH",
    "glibc": "Glibc",
    "rpm": "RPM",
    "firefox": "Firefox",
    "unix": "یونیکس",
    "linux": "لینوکس",
    "macos": "macOS",
    "haskell": "Haskell",
    # Dev general
    "api": "API",
    "cli": "CLI",
    "sdk": "SDK",
    "repo": "مخزن (repo)",
    "repository": "مخزن",
    "commit": "کامیت",
    "branch": "شاخه",
    "deploy": "استقرار",
    "deployment": "استقرار",
    "server": "سرور",
    "client": "کلاینت",
    "host": "میزبان",
    "container": "کانتینر",
    "vm": "ماشین مجازی (VM)",
    "virtualization": "مجازی‌سازی",
    "config": "پیکربندی",
    "configuration": "پیکربندی",
    "configure": "پیکربندی کردن",
    "default": "پیش‌فرض",
    "override": "بازنویسی تنظیم",
    "module": "ماژول",
    "modules": "ماژول‌ها",
    "option": "گزینه",
    "options": "گزینه‌ها",
    "attribute": "صفت / attribute",
    "attributes": "صفات",
    "expression": "عبارت",
    "expressions": "عبارات",
    "function": "تابع",
    "functions": "توابع",
    "argument": "آرگومان",
    "arguments": "آرگومان‌ها",
    "variable": "متغیر",
    "variables": "متغیرها",
    "string": "رشته",
    "boolean": "بولی",
    "integer": "عدد صحیح",
    "closure": "بستهٔ بستار (closure)",
    "sandbox": "سندباکس",
    "sandboxed": "سندباکس‌شده",
    "fetch": "واکشی",
    "download": "دانلود",
    "upload": "آپلود",
    "patch": "پچ",
    "version": "نسخه",
    "versions": "نسخه‌ها",
    "variant": "گونه / variant",
    "variants": "گونه‌ها",
    "conflict": "تداخل",
    "conflicts": "تداخل‌ها",
    "consistent": "سازگار / consistent",
    "inconsistent": "ناسازگار",
    "crash": "کرش / فروپاشی",
    "bug": "باگ",
    "debug": "اشکال‌زدایی",
    "test": "آزمون",
    "testing": "آزمون‌گیری",
    "production": "محیط عملیاتی",
    "staging": "محیط staging",
    "mutable": "تغییرپذیر",
    "immutable": "تغییرناپذیر",
    "state": "وضعیت / state",
    "stateless": "بدون state",
    "stateful": "دارای state",
}

# Extra tokens that look technical even if not in SINGLE_TERMS
# (matched via heuristic layers in tools.glossary.build).
# Common English stopwords — never treat as tech glossary candidates alone.
STOPWORDS = frozenset(
    """
    a an the and or but if then else when while for of to in on at by from with
    as is are was were be been being have has had do does did will would shall
    should can could may might must need dare ought used
    this that these those it its itself they them their theirs you your yours
    we us our ours i me my mine he him his she her hers
    not no nor so than too very just also only even still already yet
    all any both each few more most other some such same own
    about above after again against all around because before below between
    during into through under until upon within without across
    there here where what which who whom whose how why
    one two three four five six seven eight nine ten first second third
    new old many much every another such
    out up down off over again further once
    get got make made take took go went come came see saw know known
    want well back way even say said like look use used using
    something anything everything nothing
    """.split()
)
